CREATE TABLE `contract_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int NOT NULL,
	`documentId` int NOT NULL,
	`contractName` varchar(500) NOT NULL,
	`contractAnalysisStatus` enum('pending','analyzing','completed','reviewed','approved','rejected') NOT NULL DEFAULT 'pending',
	`progress` int NOT NULL DEFAULT 0,
	`executiveSummary` text,
	`complianceScore` int,
	`criticalRisks` int NOT NULL DEFAULT 0,
	`highRisks` int NOT NULL DEFAULT 0,
	`mediumRisks` int NOT NULL DEFAULT 0,
	`lowRisks` int NOT NULL DEFAULT 0,
	`veryLowRisks` int NOT NULL DEFAULT 0,
	`extractedText` text,
	`aiResponse` json,
	`aiModel` varchar(100),
	`createdById` int NOT NULL,
	`reviewedById` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `contract_analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contract_analysis_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysisId` int NOT NULL,
	`historyActionType` enum('created','analysis_started','analysis_completed','refinement_requested','refinement_completed','reviewed','approved','rejected','exported') NOT NULL,
	`description` text,
	`previousData` json,
	`newData` json,
	`userId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contract_analysis_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contract_analysis_maps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysisId` int NOT NULL,
	`partnerName` varchar(500),
	`contractType` varchar(255),
	`contractingParty` varchar(500),
	`contractedParty` varchar(500),
	`lgpdAgentType` enum('controlador','operador','controlador_conjunto','suboperador'),
	`agentTypeJustification` text,
	`contractObject` text,
	`startDate` varchar(50),
	`endDate` varchar(50),
	`commonData` text,
	`commonDataLargeScale` boolean DEFAULT false,
	`sensitiveData` text,
	`sensitiveDataLargeScale` boolean DEFAULT false,
	`hasElderlyData` boolean DEFAULT false,
	`elderlyDataDetails` text,
	`hasMinorData` boolean DEFAULT false,
	`minorDataDetails` text,
	`checklistStatus` enum('sim','nao','parcial'),
	`titularRightsDetails` text,
	`dataEliminationDetails` text,
	`legalRisks` text,
	`securityRisks` text,
	`protectionClauseDetails` text,
	`suggestedClause` text,
	`actionStatus` enum('adequado','ajustar') DEFAULT 'ajustar',
	`actionPlan` text,
	`suggestedDeadline` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contract_analysis_maps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contract_checklist_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysisId` int NOT NULL,
	`itemNumber` int NOT NULL,
	`question` text NOT NULL,
	`checklistStatus` enum('sim','nao','parcial') NOT NULL,
	`observations` text,
	`contractExcerpt` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contract_checklist_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contract_risk_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysisId` int NOT NULL,
	`contractArea` varchar(255),
	`analysisBlock` int,
	`riskDescription` text NOT NULL,
	`riskLevel` enum('1','2','3','4','5') NOT NULL,
	`potentialImpact` text,
	`requiredAction` text NOT NULL,
	`suggestedDeadline` varchar(50),
	`legalReference` text,
	`riskActionStatus` enum('pendente','em_andamento','concluido') DEFAULT 'pendente',
	`actionPlanId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contract_risk_items_id` PRIMARY KEY(`id`)
);
