DROP TABLE `access_links`;--> statement-breakpoint
DROP TABLE `action_plan_evidence`;--> statement-breakpoint
DROP TABLE `action_plans`;--> statement-breakpoint
DROP TABLE `active_ticket_templates`;--> statement-breakpoint
DROP TABLE `ai_chat_messages`;--> statement-breakpoint
DROP TABLE `ai_chat_sessions`;--> statement-breakpoint
DROP TABLE `ai_generated_results`;--> statement-breakpoint
DROP TABLE `ai_organization_instructions`;--> statement-breakpoint
DROP TABLE `ai_prompt_templates`;--> statement-breakpoint
DROP TABLE `ai_provider_configs`;--> statement-breakpoint
DROP TABLE `assessment_documents`;--> statement-breakpoint
DROP TABLE `audit_logs`;--> statement-breakpoint
DROP TABLE `clause_audit_log`;--> statement-breakpoint
DROP TABLE `compliance_assessments`;--> statement-breakpoint
DROP TABLE `compliance_responses`;--> statement-breakpoint
DROP TABLE `contract_analyses`;--> statement-breakpoint
DROP TABLE `contract_analysis_clauses`;--> statement-breakpoint
DROP TABLE `contract_analysis_history`;--> statement-breakpoint
DROP TABLE `contract_analysis_maps`;--> statement-breakpoint
DROP TABLE `contract_checklist_items`;--> statement-breakpoint
DROP TABLE `contract_risk_items`;--> statement-breakpoint
DROP TABLE `documents`;--> statement-breakpoint
DROP TABLE `evidences`;--> statement-breakpoint
DROP TABLE `ged_access_logs`;--> statement-breakpoint
DROP TABLE `ged_documents`;--> statement-breakpoint
DROP TABLE `ged_folder_templates`;--> statement-breakpoint
DROP TABLE `ged_folders`;--> statement-breakpoint
DROP TABLE `ged_permissions`;--> statement-breakpoint
DROP TABLE `global_notification_settings`;--> statement-breakpoint
DROP TABLE `governanca_action_items`;--> statement-breakpoint
DROP TABLE `governanca_agenda_items`;--> statement-breakpoint
DROP TABLE `governanca_atividade_organizacao`;--> statement-breakpoint
DROP TABLE `governanca_controls`;--> statement-breakpoint
DROP TABLE `governanca_cppd_configs`;--> statement-breakpoint
DROP TABLE `governanca_cppd_members`;--> statement-breakpoint
DROP TABLE `governanca_entregavel_organizacao`;--> statement-breakpoint
DROP TABLE `governanca_meeting_participants`;--> statement-breakpoint
DROP TABLE `governanca_meetings`;--> statement-breakpoint
DROP TABLE `governanca_mes_organizacao`;--> statement-breakpoint
DROP TABLE `governanca_mes_templates`;--> statement-breakpoint
DROP TABLE `governanca_plano_anual_organizacao`;--> statement-breakpoint
DROP TABLE `governanca_plano_anual_templates`;--> statement-breakpoint
DROP TABLE `governanca_program_milestones`;--> statement-breakpoint
DROP TABLE `governanca_program_phases`;--> statement-breakpoint
DROP TABLE `governanca_programs`;--> statement-breakpoint
DROP TABLE `lgpd_clause_template_history`;--> statement-breakpoint
DROP TABLE `lgpd_clause_templates`;--> statement-breakpoint
DROP TABLE `meudpo_settings`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `organization_notification_settings`;--> statement-breakpoint
DROP TABLE `organizations`;--> statement-breakpoint
DROP TABLE `reminder_logs`;--> statement-breakpoint
DROP TABLE `reminder_settings`;--> statement-breakpoint
DROP TABLE `response_templates`;--> statement-breakpoint
DROP TABLE `rot_operations`;--> statement-breakpoint
DROP TABLE `rot_tasks`;--> statement-breakpoint
DROP TABLE `scheduled_template_executions`;--> statement-breakpoint
DROP TABLE `simulation_checklists`;--> statement-breakpoint
DROP TABLE `simulation_decisions`;--> statement-breakpoint
DROP TABLE `simulation_events`;--> statement-breakpoint
DROP TABLE `simulation_feedback`;--> statement-breakpoint
DROP TABLE `simulation_kpis`;--> statement-breakpoint
DROP TABLE `simulation_scenarios`;--> statement-breakpoint
DROP TABLE `simulation_stakeholders`;--> statement-breakpoint
DROP TABLE `simulations`;--> statement-breakpoint
DROP TABLE `sla_metrics`;--> statement-breakpoint
DROP TABLE `third_parties`;--> statement-breakpoint
DROP TABLE `third_party_access_links`;--> statement-breakpoint
DROP TABLE `third_party_assessments`;--> statement-breakpoint
DROP TABLE `third_party_responses`;--> statement-breakpoint
DROP TABLE `ticket_attachments`;--> statement-breakpoint
DROP TABLE `ticket_calendar_events`;--> statement-breakpoint
DROP TABLE `ticket_comments`;--> statement-breakpoint
DROP TABLE `ticket_escalations`;--> statement-breakpoint
DROP TABLE `ticket_tag_associations`;--> statement-breakpoint
DROP TABLE `ticket_tags`;--> statement-breakpoint
DROP TABLE `tickets`;--> statement-breakpoint
DROP TABLE `user_invites`;--> statement-breakpoint
DROP TABLE `user_organizations`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `organizationId`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `avatarUrl`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `phone`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `isActive`;